export interface Product {
  id: number;
  name: string;
  price: string;
  category: string;
  image: string;
  affiliateLink: string;
  rating: number;      // Adicione esta linha
  sold: string;        // Adicione esta linha
  featured?: boolean;  // Adicione esta linha
  freeShipping?: boolean; // Adicione esta linha
  origin: 'BR' | 'INT';
}

export const products: Product[] = [
  {
        id: 1,
        name: "WATERSY Copo garrafa Térmica Inox 591ml Parede Dupla tampa Canudo Premium",
        origin: "BR",
        price: "43.90",
        category: "Cozinha",
        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mcsz2r14c6k2cf.webp", 
        affiliateLink: "https://s.shopee.com.br/2B8tUQn4nB?share_channel_code=1",
        featured: true,
        rating: 4.9,
        sold: "1mil+"
      },
  {
    id: 2,
    name: "Copo Térmico 1200ml Personalizado com o Nome - Stitch Premium",
    origin: "BR",
    price: "47,03",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjrflddx5fra59.webp",
    category: "Cozinha",
    affiliateLink: "https://s.shopee.com.br/3VeH6rTNJn?share_channel_code=1",
    rating: 4.8,
    sold: "2,5mil+"
  },
  {
    id: 3,
    name: "Ventilador de Coluna 103cm-130cm ajuste de altura livremente, ventilador de pé 110v/220v",
    origin: "BR",
    price: "86.00", // Preço inicial que aparece no print
    category: "Eletro",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m0t0oki833pde3.webp", 
    affiliateLink: "https://s.shopee.com.br/4VWiRfaX1y?share_channel_code=1",
    featured: true,  // Marcado como destaque pelo alto volume de vendas
    rating: 4.6,    // Nota do produto no print
    sold: "20mil+"   // Quantidade vendida no print
  },
  {
    id: 4,
    name: "Tábua de Corte Profissional em Aço Inoxidável 304, Antimofo e Antibacteriano, Ferramenta de Cozinha",
    origin: "BR",
    price: "28.99", // Preço promocional que aparece no print
    category: "Cozinha",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7ra24-mbjxrrwigjnx20.webp", // Link sugerido da imagem
    affiliateLink: "https://s.shopee.com.br/8AQ6hn0xeu?share_channel_code=1",
    featured: false, 
    rating: 4.8,    // Nota do produto que aparece no print
    sold: "4mil+"   // Quantidade vendida que aparece no print
  },
  {
    id: 5,
    name: "Copão Garrafa Tumbler Zona Criativa Com Canudo e Pingente Stitch Harry Potter Original",
    origin: "BR",
    price: "129.90",
    category: "Cozinha",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mgs3a7bgi7t0da.webp", 
    affiliateLink: "https://s.shopee.com.br/W0fZuBhId?share_channel_code=1",
    featured: false,
    rating: 4.9,
    sold: "197"
  },
  {
    id: 6,
    name: "Ar Condicionado Mini Portátil USB Climatizador Umidificador Ventilador com LED Para Quarto Sala Escritório Mesa",
    origin: "BR",
    price: "39.98",
    category: "Eletronico",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mff3qwsuc8hs40@resize_w450_nl.webp", 
    affiliateLink: "https://s.shopee.com.br/4fqEXuIHtQ?share_channel_code=1",
    rating: 4.8,
    sold: "4mil+"
  },
  {
    id: 7,
    name: "Cortina Blackout Para Quarto Sala Cozinha PVC Corta 100% Luz 2,80 Largura x 2,30 Altura",
    origin: "BR",
    price: "32.97",
    category: "Casa & Decoracao",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m7die869hkr01f@resize_w450_nl.webp",
    affiliateLink: "https://s.shopee.com.br/30huejKM8X?share_channel_code=1",
    rating: 4.7,
    sold: "80mil+"
  },
  {
    id: 8,
    name: "Espelho Decorativo Redondo para Escritório Sala Quarto Banheiro com LED 60cm + Suporte",
    origin: "BR",
    price: "56.30",
    category: "Casa & Decoracao",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mfy5748s8tmt52.webp",
    affiliateLink: "https://s.shopee.com.br/6VHmp6HaIS?share_channel_code=1",
    rating: 4.9,
    sold: "1mil+"
  },
  {
    id: 9,
    name: "Escorredor de Louça Duplo Multifuncional Suporte para Pratos, Talheres e Tábua de Corte",
    origin: "BR",
    price: "91.00",
    category: "Cozinha",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mg4h3ptpbsw74e.webp",
    affiliateLink: "https://s.shopee.com.br/4Ats2kag16?share_channel_code=1",
    rating: 4.7,
    sold: "8mil+"
  },
  {
    id: 10,
    name: "Vestido Longo Feminino com Forro e Bojo Manga Variada Confortável e Leve",
    origin: "BR",
    price: "70.30",
    category: "Moda",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mbaadmixtnrj1b.webp",
    affiliateLink: "https://s.shopee.com.br/5q261lILPS?share_channel_code=1",
    rating: 4.9,
    sold: "984"
  },
  {
    id: 11,
    name: "Kit Relógio Feminino com Colar, Pulseira e Brinco Rma13",
    origin: "BR",
    price: "33.65",
    category: "Acessórios Femininos",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rcdn-lsymzl4ljwghb6.webp",
    affiliateLink: "https://s.shopee.com.br/8AQ0nvhUV4?share_channel_code=1",
    rating: 4.5,
    sold: "8mil+"
  },
  {
    id: 12,
    name: "Perfume Original Caviar Night 100ml Paris Elysses",
    origin: "BR",
    price: "78.90",
    category: "Perfumes",
    image: "https://down-br.img.susercontent.com/file/8a26f73aeef9078e605ca74230cc7d8a.webp",
    affiliateLink: "https://s.shopee.com.br/AKUVNAj5rB?share_channel_code=1",
    rating: 4.9,
    sold: "40mil+"
  },
  {
    id: 13,
    name: "Perfume Woman Love Le Parfum 75ml",
    origin: "BR",
    price: "29.90",
    category: "Perfumes",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m1c03v282u9s86.webp",
    affiliateLink: "https://s.shopee.com.br/6VHmo292zv?share_channel_code=1",
    rating: 4.8,
    sold: "4mil+"
  },
  {
    id: 14,
    name: "Kit SOS Cachos Coco Família com Creme de Pentear 1kg Salon Line",
    origin: "BR",
    price: "80.00",
    category: "Cuidados com Cabelo",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-8258n-mfukepwehqtk34.webp",
    affiliateLink: "https://s.shopee.com.br/5q260eFYWs?share_channel_code=1",
    rating: 4.9,
    sold: "10mil+"
  },
  {
    id: 15,
    name: "Gelatina Todecacho Não Sai da Minha Cabeça 1kg Salon Line",
    origin: "BR",
    price: "37.49",
    category: "Cuidados com Cabelo",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m0u7vsq0duuv9a.webp",
    affiliateLink: "https://s.shopee.com.br/7fTkBukSrU?share_channel_code=1",
    rating: 4.9,
    sold: "100mil+"
  },
  {
    id: 16,
    name: "Kit 4 Top Feminino com Bojo Microfibra Alça Larga Lingerie Confortável",
    origin: "BR",
    price: "59.99",
    category: "Lingerie Feminina",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-me7mk3kh1uyo54.webp",
    affiliateLink: "https://s.shopee.com.br/1gCX2cj6nP?share_channel_code=1",
    rating: 4.8,
    sold: "3mil+"
  },
  {
    id: 17,
    name: "Fita de Medição Corporal Antropométrica com Cálculo de IMC",
    origin: "BR",
    price: "45.90",
    category: "Saúde e Bem-Estar",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mbnftsox19bscb.webp",
    affiliateLink: "https://s.shopee.com.br/5fiVy6gHh3?share_channel_code=1",
    rating: 4.9,
    sold: "20mil+"
  },
  {
    id: 18,
    name: "Body Splash Cabelo e Corpo Xêrosa Glamour Chic 200ml",
    origin: "BR",
    price: "25.81",
    category: "Perfumaria",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-82596-mfuz10j0hpn022.webp",
    affiliateLink: "https://s.shopee.com.br/7VAA9LPCSY?share_channel_code=1",
    rating: 4.7,
    sold: "5mil+"
  },
  {
    id: 19,
    name: "Lixeira Cesto de Lixo Automática Suspensa 9 Litros para Banheiro Cozinha Escritório",
    origin: "BR",
    price: "24.90",
    category: "Organização e Limpeza",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mcqkrblr07wha2.webp",
    affiliateLink: "https://s.shopee.com.br/9fEdVnGtei?share_channel_code=1",
    rating: 4.8,
    sold: "10mil+"
  },
  {
    id: 20,
    name: "Balança Digital de Bioimpedância Bluetooth Corporal até 180kg com Resultado no Celular",
    origin: "BR",
    price: "31.80",
    category: "Saúde e Bem-Estar",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lzib4imuteed82.webp",
    affiliateLink: "https://s.shopee.com.br/1qVmBKqnmO?share_channel_code=1",
    rating: 4.9,
    sold: "10mil+"
  },
  {
    id: 21,
    name: "Boia Inflável em Forma de Donut para Crianças, Adolescentes e Adultos 60/70/90/120 cm",
    origin: "BR",
    price: "14.16",
    category: "Lazer e Piscina",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-822zv-mi5mvwyxc8p4fc.webp",
    affiliateLink: "https://s.shopee.com.br/20pTXtSYem?share_channel_code=1",
    rating: 4.7,
    sold: "73"
  },
  {
    id: 22,
    name: "Jogo de Xícaras para Café e Chá Rosa com Suporte Kit 4 Canecas Poá",
    origin: "BR",
    price: "57.00",
    category: "Cozinha",
    image: "https://down-br.img.susercontent.com/file/br-11134201-23010-yz3xtrmccemve6.webp",
    affiliateLink: "https://s.shopee.com.br/7pmnXRj7xu?share_channel_code=1",
    rating: 4.9,
    sold: "3,2mil+"
  },
  {
    id: 23,
    name: "Lovito Maiô Feminino com Decote em V com Detalhe em Metal LNL42135",
    origin: "INT",
    price: "49.42",
    category: "Moda Praia",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rd49-m7hg9lqo58fq0f.webp",
    affiliateLink: "https://s.shopee.com.br/2LRqz2XoAI?share_channel_code=1",
    rating: 4.9,
    sold: "20mil+"
  },
  {
    id: 24,
    name: "Caixa Térmica Cooler Multifuncional 5 em 1 com 2 Mesas e 2 Banquetas Integradas 32 Litros",
    origin: "BR",
    price: "269.99",
    category: "Lazer e Camping",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lt2g69s846x912.webp",
    affiliateLink: "https://s.shopee.com.br/AUnT7FcTzd?share_channel_code=1",
    rating: 4.8,
    sold: "6mil+"
  },
  {
    id: 25,
    name: "Boia Rede Flores para Piscina Cama Flutuante Adulto",
    origin: "BR",
    price: "34.99",
    category: "Lazer e Piscina",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-md7i9hihwzea5d.webp",
    affiliateLink: "https://s.shopee.com.br/W07ChNSpI?share_channel_code=1",
    rating: 4.9,
    sold: "295"
  },
  {
    id: 26,
    name: "Mangueira de Jardim Reforçada Siliconada Trançada 1/2 x 3 mm Azul",
    origin: "BR",
    price: "104.85",
    category: "Jardim e Exterior",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mct971ze8etd2e.webp",
    affiliateLink: "https://s.shopee.com.br/6AeTwTZeFi?share_channel_code=1",
    rating: 4.9,
    sold: "716"
  },
  {
    id: 27,
    name: "Trena Longa 50 Metros em Fibra de Vidro com Manivela Profissional",
    origin: "BR",
    price: "19.80",
    category: "Ferramentas",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lymv1zolpa1x2d.webp",
    affiliateLink: "https://s.shopee.com.br/7AWugdjV7Y?share_channel_code=1",
    rating: 4.9,
    sold: "5mil+"
  },
  {
    id: 28,
    name: "Climatizador de Ar Ventisol Portátil Clin 60 Pro 60 Litros 150W Branco/Cinza",
    origin: "BR",
    price: "839.99",
    category: "Climatização",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mgz4o2wfi77r09.webp",
    affiliateLink: "https://s.shopee.com.br/2LRagscza2?share_channel_code=1",
    rating: 4.8,
    sold: "3mil+"
  },
  {
    id: 29,
    name: "Tapete Gelado Refrescante para Cachorro e Gato Pet 50cm x 65cm",
    origin: "BR",
    price: "39.90",
    category: "Pet Shop",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lyf7wg0kd9xx62.webp",
    affiliateLink: "https://s.shopee.com.br/2Vl0c8Y9tD?share_channel_code=1",
    rating: 4.8,
    sold: "4mil+"
  },
  {
      id: 30,
        name: "Kit 10 Pedra Porosa para Compressor de Ar Oxigenação de Aquário",
          origin: "BR",
            price: "25.70",
              category: "Aquarismo",
                image: "https://down-br.img.susercontent.com/file/sg-11134201-82612-mjoa2d92vvnr58@resize_w900_nl.webp",
                  affiliateLink: "https://s.shopee.com.br/6VHx23QO6a?share_channel_code=1",
                    rating: 4.9,
                      sold: "1mil+"
                      },
                      {
                        id: 31,
                        name: "Carregador Portátil Power Bank Solar 20000mAh com Cabos 5 em 1 e Lanterna LED",
                        origin: "BR",
                        price: "60.99",
                        category: "Acessórios para Celular",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdxx-md0gws953auv02.webp",
                        affiliateLink: "https://s.shopee.com.br/5L5zfRVuiz?share_channel_code=1",
                        rating: 4.6,
                        sold: "10mil+"
                      },
                      {
                        id: 32,
                        name: "Colchão Inflável Casal para Camping e Praia Suporta 300kg com Bomba de Ar Manual Bestway",
                        origin: "BR",
                        price: "139.90",
                        category: "Lazer e Camping",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mc2cgtyxynjb15.webp",
                        affiliateLink: "https://s.shopee.com.br/2B8xuTiYgk?share_channel_code=1",
                        rating: 4.9,
                        sold: "20mil+"
                      },
                      {
                        id: 33,
                        name: "Mesa Dobrável Vira Maleta com Alça Portátil 1,80m para Camping, Pesca e Área Externa",
                        origin: "BR",
                        price: "279.90",
                        category: "Lazer e Camping",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m7qvt44tnhqsce.webp",
                        affiliateLink: "https://s.shopee.com.br/14TKwjtca?share_channel_code=1",
                        rating: 4.9,
                        sold: "9mil+"
                      },
                      {
                        id: 34,
                        name: "Mochila Grande Impermeável Executiva Reforçada para Notebook com Cadeado e Bolso Antifurto",
                        origin: "BR",
                        price: "68.99",
                        category: "Mochilas e Bolsas",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lzhs324fmp1d0e.webp",
                        affiliateLink: "https://s.shopee.com.br/7Kr4507uAK?share_channel_code=1",
                        rating: 4.8,
                        sold: "20mil+"
                      },
                      {
                        id: 35,
                        name: "Fatiador Profissional Multifuncional 16 em 1 em Aço Inoxidável",
                        origin: "BR",
                        price: "35.99",
                        category: "Cozinha",
                        image: "https://down-tx-br.img.susercontent.com/br-11134207-81z1k-mhjfa9ir0mbq21.webp",
                        affiliateLink: "https://s.shopee.com.br/5firohbgci",
                        rating: 4.8,
                        sold: "30mil+"
                      },
                      {
                        id: 36,
                        name: "Berço Americano Vira Cama com Cama Auxiliar, Trocador e Gaveteiro Branco",
                        origin: "BR",
                        price: "1189.90",
                        category: "Bebês e Infantil",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdyf-lzl6u0bnxppwee.webp",
                        affiliateLink: "https://s.shopee.com.br/6VHyqDbYWX",
                        rating: 4.9,
                        sold: "93"
                      },
                      {
                        id: 37,
                        name: "Quarto de Bebê Completo 100% MDF com Cômoda, Berço e Guarda-Roupa Nina Branco/Amadeirado",
                        origin: "BR",
                        price: "1099.99",
                        category: "Bebês e Infantil",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdwo-mctnwoncftj078.webp",
                        affiliateLink: "https://s.shopee.com.br/50TBD8cPiS",
                        rating: 4.7,
                        sold: "1mil+"
                      },
                      {
                        id: 38,
                        name: "Berço Cômoda Meu Bebê Multimóveis MP4309 com Colchão Incluso",
                        origin: "BR",
                        price: "546.10",
                        category: "Bebês e Infantil",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rep8-m1o8e8gcec2va5.webp",
                        affiliateLink: "https://s.shopee.com.br/10x2SKmqOs",
                        rating: 4.8,
                        sold: "530"
                      },
                      {
                        id: 39,
                        name: "Quarto de Bebê Completo com Berço Americano Ben 3 em 1 e Cômoda Uli 4 Gavetas 100% MDF",
                        origin: "BR",
                        price: "949.90",
                        category: "Bebês e Infantil",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdwo-lzi1v6clcmgn4c.webp",
                        affiliateLink: "https://s.shopee.com.br/8zzJywGH8n",
                        rating: 4.9,
                        sold: "3mil+"
                      },
                      {
                        id: 40,
                        name: "Quarto Infantil com Berço e Cômoda Olívia Multimóveis Branco",
                        origin: "BR",
                        price: "859.99",
                        category: "Bebês e Infantil",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7qvdv-lhxg19xeo853c1@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/2qOgdrp1Zq",
                        rating: 4.8,
                        sold: "1mil+"
                      },
                      {
                        id: 41,
                        name: "Kit 4 Banquetas Eiffel Giratórias Estofadas com Encosto para Sala de Jantar",
                        origin: "BR",
                        price: "769.90",
                        category: "Móveis",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjqyjw1rdjpiba.webp",
                        affiliateLink: "https://s.shopee.com.br/2qOge8Z9Sj",
                        rating: 4.8,
                        sold: "348"
                      },
                      {
                        id: 43,
                        name: "Banqueta Plástica Multiuso Dobrável Capacidade 150kg Vonder",
                        origin: "BR",
                        price: "59.90",
                        category: "Utilidades Domésticas",
                        image: "https://down-br.img.susercontent.com/file/b608049528cc70588dd915dd1b058c81.webp",
                        affiliateLink: "https://s.shopee.com.br/1gCjGbt6s0",
                        rating: 4.9,
                        sold: "477"
                      },
                      {
                        id: 44,
                        name: "Mochila Unissex com Desenhos Reforçada Grande Capacidade Antifurto",
                        origin: "BR",
                        price: "",
                        category: "Mochilas e Bolsas",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7qukw-lhz5qxwaj6mm64.webp",
                        affiliateLink: "https://s.shopee.com.br/2LSQ3z90Hx",
                        rating: 4.9,
                        sold: "2mil+"
                      },
                      {
                        id: 45,
                        name: "Banqueta Multiuso Dobrável com Alça Suporta até 150kg para Camping Pesca e Rancho",
                        origin: "BR",
                        price: "",
                        category: "Lazer e Camping",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mdvrn6zbkfsx13.webp",
                        affiliateLink: "https://s.shopee.com.br/40ae39DVFQ",
                        rating: 4.9,
                        sold: "1mil+"
                      },
                      {
                        id: 46,
                        name: "Banquinho Banco Banqueta Dobrável Portátil 21cm Arqplast Preta",
                        origin: "BR",
                        price: "21.00",
                        category: "Utilidades Domésticas",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7ra30-m590zm0l55sn7e.webp",
                        affiliateLink: "https://s.shopee.com.br/14VHw7Uq0",
                        rating: 4.7,
                        sold: "6mil+"
                      },
                      {
                        id: 47,
                        name: "Tenda Cabana Gazebo Dobrável em Alumínio com Bolsa de Transporte 3x3x2,5m Erbmaquinas",
                        origin: "BR",
                        price: "499.99",
                        category: "Lazer e Camping",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rblz-m5xaxiynu2tmb8.webp",
                        affiliateLink: "https://s.shopee.com.br/8pftrlXiKe",
                        rating: 4.9,
                        sold: "904"
                      },
                      {
                        id: 48,
                        name: "Tenda de Praia Sanfonada Mor X-Flex Gazebo 3x3 Articulado com Pé de Alumínio",
                        origin: "BR",
                        price: "",
                        category: "Lazer e Camping",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lrzy53l2noy5d3.webp",
                        affiliateLink: "https://s.shopee.com.br/7pnMg23l2q",
                        rating: 4.9,
                        sold: "7mil+"
                      },
                      {
                        id: 49,
                        name: "Tenda Gazebo 3 x 6 Metros em Aço Dobrável Várias Cores BEL",
                        origin: "BR",
                        price: "",
                        category: "Lazer e Camping",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rblo-lmt1tl7jmhqyb2.webp",
                        affiliateLink: "https://s.shopee.com.br/7fTwTs0pEH",
                        rating: 4.6,
                        sold: "215"
                      },
                      {
                        id: 50,
                        name: "Lampião Luminária Solar para Camping com Carregador USB LED Lanterna",
                        origin: "BR",
                        price: "28.50",
                        category: "Lazer e Camping",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rd6p-lwkbgx5q0joxc9.webp",
                        affiliateLink: "https://s.shopee.com.br/40ae7JRwJB",
                        rating: 4.8,
                        sold: "10mil+"
                      },
                      {
                        id: 51,
                        name: "Conjunto Academia Top Fitness e Legging Cintura Alta Zero Transparência Suplex Strep Original",
                        origin: "BR",
                        price: "R$49,90 - R$59,90",
                        category: "Moda Fitness",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-me5wxzf59l34eb@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/6VHz6IqnFV",
                        rating: 4.7,
                        sold: "4mil+"
                      },
                      {
                        id: 52,
                        name: "Kit Jogo 4 Xícaras Mini Wolff 100ml Café Cafézinho Cantinho Café Pearl Bolinhas",
                        origin: "BR",
                        price: "29.99",
                        category: "Casa e Cozinha",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rat8-maiuwgvwqq6b4d.webp",
                        affiliateLink: "https://s.shopee.com.br/6KyYuGOUfK",
                        rating: 5.0,
                        sold: "247"
                      },
                      {
                        id: 53,
                        name: "Mesinha Dobrável Portátil Petisqueira para Piscina Pescaria Camping e Praia",
                        origin: "BR",
                        price: "69,90",
                        category: "Lazer e Camping",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m9spj4nmrbiaf4.webp",
                        affiliateLink: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m9spj4nmrbiaf4.webp",
                        rating: 4.8,
                        sold: "335"
                      },
                      {
                        id: 54,
                        name: "Espelho Retangular EL14 Corpo Inteiro 170x70cm com LED Jateado Luz Branca e Amarela",
                        origin: "BR",
                        price: "509,15",
                        category: "Casa & Decoração",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjygj3rau6tife.webp",
                        affiliateLink: "https://s.shopee.com.br/6VHz6yMUUv",
                        rating: 4.7,
                        sold: "1mil+"
                      },
                      {
                        id: 55,
                        name: "Tapete Passadeira Felpudo Peludo para Corredor Sala Quarto Beira de Cama",
                        origin: "BR",
                        price: "15,50",
                        category: "Casa & Decoração",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-macr7gj8pdvza4.webp",
                        affiliateLink: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-macr7gj8pdvza4.webp",
                        rating: 4.4,
                        sold: "50mil+"
                      },
                      {
                        id: 56,
                        name: "Organizador de Ovos com 4 Espaços e Andares",
                        origin: "BR",
                        price: "17,97 - 72,00",
                        category: "Casa & Organização",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-8262i-mjbblzuwk0lh18.webp",
                        affiliateLink: "https://s.shopee.com.br/4LDUYA1JtD",
                        rating: 4.8,
                        sold: "6mil+"
                      },
                      {
                        id: 57,
                        name: "Cortina Blackout em PVC 100% Corta Luz 2,80m x 2,30m para Quarto Sala ou Cozinha",
                        origin: "BR",
                        price: "",
                        category: "Casa & Decoração",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m84shxe4v8c1d9.webp",
                        affiliateLink: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m84shxe4v8c1d9.webp",
                        rating: 4.7,
                        sold: "80mil+"
                      },
                      {
                        id: 58,
                        name: "Parafusadeira e Furadeira de Impacto com Maleta, Duas Baterias e Kit 28 Peças Bivolt 110V/220V",
                        origin: "BR",
                        price: "133.90",
                        category: "Ferramentas",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjnlqrkzxpty83.webp",
                        affiliateLink: "https://s.shopee.com.br/4LDUZpPi1W",
                        rating: 4.8,
                        sold: "70mil+"
                      },
                      {
                        id: 59,
                        name: "Esfoliante Corporal e Facial Frutas Poran – Escolha o Seu Tipo",
                        origin: "BR",
                        price: "12.25",
                        category: "Beleza e Cuidados Pessoais",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lt44nts8bxgy8b.webp",
                        affiliateLink: "https://s.shopee.com.br/2VlqOrrWcf",
                        rating: 4.8,
                        sold: "20mil+"
                      },
                      {
                        id: 60,
                        name: "Kit 3 Conjuntos Academia Feminino Top + Legging Zero Transparência Fitness",
                        origin: "BR",
                        price: "149.90",
                        category: "Moda Fitness Feminina",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mf8le3twx6o795@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/50TBNehUX3",
                        rating: 4.7,
                        sold: "2mil+"
                      },
                      {
                        id: 61,
                        name: "Tapete Belga Estampado Para Sala e Quarto de Luxo – Lançamentos Exclusivos",
                        origin: "BR",
                        price: "64.99 - 229.99",
                        category: "Casa e Decoração",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-meq6c1qewzya7b@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/LhLpBN5u7",
                        rating: 4.7,
                        sold: "722"
                      },
                      {
                        id: 62,
                        name: "Copo Térmico Grande 1200ml em Aço Inox com Alça e Canudo de Metal",
                        origin: "BR",
                        price: "37.49",
                        category: "Cozinha e Utilidades",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m9fw9t7ulx4yb8.webp",
                        affiliateLink: "https://s.shopee.com.br/3B1XEFRaUL",
                        rating: 4.8,
                        sold: "320"
                      },
                      {
                        id: 63,
                        name: "Jogo de Lençol Percal 180 Fios 100% Algodão – Todos os Tamanhos",
                        origin: "BR",
                        price: "56.70 - 75.95",
                        category: "Cama, Mesa e Banho",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mflnn6x2vldw1e.webp",
                        affiliateLink: "https://s.shopee.com.br/9KcAZobz85",
                        rating: 4.8,
                        sold: "2mil+"
                      },
                      {
                        id: 64,
                        name: "Saia Tule Tutu Brilho Colorida 40cm com LED para Carnaval, Ballet, Dança e Fantasia",
                        origin: "BR",
                        price: "26.90",
                        category: "Fantasias e Festas",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mi4m89zygd1f72.webp",
                        affiliateLink: "https://s.shopee.com.br/7VAWOpvGgn",
                        rating: 4.8,
                        sold: "1mil+"
                      },  
                      {
                        id: 65,
                        name: "Robô Aspirador Inteligente 3 em 1 para Limpeza Doméstica Silencioso Ideal para Casa com Pets E4",
                        origin: "BR",
                        price: "58.99",
                        category: "Casa e Limpeza",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mgt001m9v6kkb1.webp",
                        affiliateLink: "https://s.shopee.com.br/W0m43FdQJ",
                        rating: 4.4,
                        sold: "7mil+"
                      },
                      {
                        id: 66,
                        name: "Par de Baquetas 7A Liverpool Sensation Grip Series com Grip EVA",
                        origin: "BR",
                        price: "37.10",
                        category: "Instrumentos Musicais",
                        image: "https://down-br.img.susercontent.com/file/2e34be6f3c55ef00e0dc3b2f14bdda88.webp",
                        affiliateLink: "https://s.shopee.com.br/9fF0z4yDy4",
                        rating: 4.9,
                        sold: "693"
                      },
                      {
                        id: 67,
                        name: "Kit 8 Unidades de Vasinho Decorativo de Gesso com Cactus e Plantas Artificiais",
                        origin: "BR",
                        price: "27.90",
                        category: "Casa e Decoração",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mi20fuptfn5v70.webp",
                        affiliateLink: "https://s.shopee.com.br/BNvjV7ITi",
                        rating: 4.3,
                        sold: "10mil+"
                      },
                      {
                        id: 68,
                        name: "Kit 3 Nichos Triplos Prateleiras Organizadoras para Banheiro em MDF Preto ou Branco",
                        origin: "BR",
                        price: "49.99 - 89.99",
                        category: "Casa e Decoração",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-maupqz4w6iux4b.webp",
                        affiliateLink: "https://s.shopee.com.br/1BGSvRj3zD",
                        rating: 4.4,
                        sold: "10mil+"
                      },  
                      {
                        id: 69,
                        name: "Mochila feminina casual e versátil leve e à prova d'água com grande capacidade para estudantes",
                        origin: "BR",
                        price: "57.89",
                        category: "Bolsas e Mochilas",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m78ryz9a1t4i9a.webp",
                        affiliateLink: "https://s.shopee.com.br/4Au4V9K8Jw",
                        rating: 4.8,
                        sold: "7mil+"
                      }, 
                      {
                        id: 70,
                        name: "Suporte Para Celular e Tablet Ergonômico Dobrável E Ajustável Apoio De Mesa",
                        origin: "BR",
                        price: "10.00 - 23.88",
                        category: "Acessórios de Celular",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m9eie10539dl15@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/8fMTwikQYr",
                        rating: 4.9,
                        sold: "1mil+"
                      },   
                      {
                        id: 71,
                        name: "KIT Cabo USB De 4 Em 1 Carregador Celular USB Tipo C Disponível para iP 1 Metro 6A Preto",
                        origin: "BR",
                        price: "",
                        category: "Acessórios de Celular",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lyk9jpe98j6ta8@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/5fisNRCGBc",
                        rating: 4.8,
                        sold: "268"
                      },   
                      {
                        id: 72,
                        name: "Cabo USB-C 4 em 1, 1 m com carregamento rápido de 65W múltiplas portas compatível com iPhone 16/15/14/13/12/Pro Samsung",
                        origin: "BR",
                        price: "13.90",
                        category: "Acessórios de Celular",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-821d6-mh6ik4532djge1.webp",
                        affiliateLink: "https://s.shopee.com.br/9fF18wsr6m",
                        rating: 4.9,
                        sold: "71"
                      },   
                      {
                        id: 73,
                        name: "Regua Cabo Hub Usb 2.0 De 4 ou 7 Portas Rápidas Extensão Usb Pc",
                        origin: "BR",
                        price: "17.50",
                        category: "Informática",
                        image: "https://down-br.img.susercontent.com/file/br-11134211-81z1k-melzvki0hjb760.webp",
                        affiliateLink: "https://s.shopee.com.br/6pupm6uLot",
                        rating: 4.8,
                        sold: "10mil+"
                      },      
                      {
                        id: 74,
                        name: "N35 Fone De Ouvido Sem Fio Bluetooth 5.0 Tws Com Cancelamento De Ruído Super Bass/Música/Jogos",
                        origin: "BR",
                        price: "32.99",
                        category: "Áudio",
                        image: "https://down-br.img.susercontent.com/file/br-11134201-23010-km7ko1rx4gmvd1.webp",
                        affiliateLink: "https://s.shopee.com.br/3VeNo5DYP3",
                        rating: 4.6,
                        sold: "10mil+"
                      },    
                      {
                        id: 75,
                        name: "Watch X Smartwatch Relogio Serie 10 Amoled Nfc Chat GPT Original",
                        origin: "BR",
                        price: "194.79",
                        category: "Smartwatches",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjpxbwvx3q4hcf.webp",
                        affiliateLink: "https://s.shopee.com.br/4LDUnz5USz",
                        rating: 4.8,
                        sold: "10mil+"
                      },  
                      {
                        id: 76,
                        name: "Victoria's Secret Body Splash 250ml Original lmportado Realce seu charme e aproveite a fragrância",
                        origin: "BR",
                        price: "89.90 - 99.90",
                        category: "Beleza e Perfumaria",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mi21wbw03z0i87@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/5L62048tO6",
                        rating: 4.4,
                        sold: "305"
                      }, 
                      {
                        id: 77,
                        name: "Kit 10 Peças Infantil Menino com Bermuda e Camiseta para o Dia a Dia em Algodão",
                        origin: "BR",
                        price: "89.99",
                        category: "Moda Infantil",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lvucn40fzxyt82.webp",
                        affiliateLink: "https://s.shopee.com.br/gKK4pteIa",
                        rating: 4.9,
                        sold: "9mil+"
                      },
                      {
                        id: 78,
                        name: "Kit 10 Peças Body e Calça Canelado Bebê 100% Algodão com 5 Bodys e 5 Calças Antialérgico",
                        origin: "BR",
                        price: "89.90",
                        category: "Moda Infantil",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lnumuy1ew8gc96.webp",
                        affiliateLink: "https://s.shopee.com.br/1gCkg4pA90?share_channel_code=1",
                        rating: 4.6,
                        sold: "10mil+"
                      },
                      {
                        id: 79,
                        name: "Kit 10 Peças de Roupas para Bebê Menino com 5 Bodys Manga Longa e 5 Calças Mijão",
                        origin: "BR",
                        price: "",
                        category: "Moda Bebê",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lxu16wp0dcxrde.webp",
                        affiliateLink: "https://s.shopee.com.br/AABIoABctK?share_channel_code=1",
                        rating: 4.9,
                        sold: "10mil+"
                      },
                      {
                        id: 80,
                        name: "Kit 4 Capas de Almofadas Decorativas 45x45 cm para Sala, Quarto e Escritório",
                        origin: "BR",
                        price: "11.90",
                        category: "Casa e Decoração",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mcgs7qhqd7aqad.webp",
                        affiliateLink: "https://s.shopee.com.br/1BGaywUYAJ",
                        rating: 4.6,
                        sold: "2mil+"
                      },      
                      {
                        id: 81,
                        name: "Capa de Chuva para Sapato Premium Protetor Impermeável para Tênis e Calçados de Motoqueiro",
                        origin: "BR",
                        price: "",
                        category: "Acessórios de Moda",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lwk0nro3aahebd.webp",
                        affiliateLink: "https://s.shopee.com.br/9fF96emto9",
                        rating: 4.8,
                        sold: "670"
                      },  
                      {
                        id: 83,
                        name: "Quadro Decorativo Trio Gratidão Ramo de Trigo Prosperidade Branco Moderno para Sala, Hall e Escritório",
                        origin: "BR",
                        price: "",
                        category: "Casa e Decoração",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mavzlumhjtsf85.webp",
                        affiliateLink: "https://s.shopee.com.br/9zrzVOvjeC",
                        rating: 4.7,
                        sold: "6mil+"
                      },    
                      {
                        id: 84,
                        name: "Kit Gamer Completo para Celular com Headset, Teclado, Mouse e Hub USB Tipo C ou V8",
                        origin: "BR",
                        price: "",
                        category: "Eletrônicos e Games",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-ma8u3vwko8l5e5.webp",
                        affiliateLink: "https://s.shopee.com.br/7AXo8MB4j2",
                        rating: 4.8,
                        sold: "2mil+"
                      },       
                      {
                        id: 85,
                        name: "WD VEST Biquíni Plus Size com Estilo, Conforto e Perfeito Caimento 2025 XX297",
                        origin: "BR",
                        price: "",
                        category: "Moda Praia",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m6jpwxmo83zkde.webp",
                        affiliateLink: "https://s.shopee.com.br/5q2QXzivgX",
                        rating: 4.7,
                        sold: "156"
                      },        
                      {
                        id: 86,
                        name: "Jogo Americano Areia Impermeável em PVC com 6 Lugares",
                        origin: "BR",
                        price: "",
                        category: "Cozinha e Mesa",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m8679o5qauc1c2.webp",
                        affiliateLink: "https://s.shopee.com.br/1VtRO66ofD",
                        rating: 4.8,
                        sold: "270"
                      },
                      {
                        id: 87,
                        name: "Colar Feminino Personalizado Semi Joia 17mm com Foto Gravada 45cm Banho Ouro 18k",
                        origin: "BR",
                        price: "",
                        category: "Joias e Acessórios",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mdyouuexi58j3b@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/20phz8bHaH",
                        rating: 4.9,
                        sold: "3mil+"
                      },
                      {
                        id: 88,
                        name: "Jogo de Chave Catraca Reversível com 40 ou 46 Peças em Maleta Completa de Ferramentas",
                        origin: "BR",
                        price: "",
                        category: "Ferramentas",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mfrvxdr9i96v11.webp",
                        affiliateLink: "https://s.shopee.com.br/3B1fNSx7wG",
                        rating: 4.8,
                        sold: "200mil+"
                      },    
                      {
                        id: 89,
                        name: "Conjunto Feminino Top + Calça Leg com Saia Tapa Bumbum em Suplex para Academia Plus Size",
                        origin: "BR",
                        price: "",
                        category: "Moda Fitness",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mesoi04veosi08.webp",
                        affiliateLink: "https://s.shopee.com.br/8zzSKJ2tGd",
                        rating: 4.5,
                        sold: "302"
                      },
                      {
                        id: 90,
                        name: "Fone de Ouvido Bluetooth com Orelhas de Gato e Luz Colorida sem Fio X4/X2",
                        origin: "BR",
                        price: "",
                        category: "Eletrônicos",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mhhapwz9asjn65.webp",
                        affiliateLink: "https://s.shopee.com.br/1BGcCjFLI5",
                        rating: 4.7,
                        sold: "10mil+"
                      },    
                      {
                        id: 91,
                        name: "Kit Organizador com Prateleira para Banheiro e Suporte para Papel Higiênico",
                        origin: "BR",
                        price: "",
                        category: "Casa e Banheiro",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mf8omhr8to9386.webp",
                        affiliateLink: "https://s.shopee.com.br/9zs0jSDjOM",
                        rating: 4.7,
                        sold: "10mil+"
                      },
                      {
                        id: 92,
                        name: "Kit Treino Funcional com Halteres, Barra, Supino e Kettlebell 10kg, 15kg ou 20kg",
                        origin: "BR",
                        price: "",
                        category: "Fitness e Musculação",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-me06pxvjxkaq62.webp",
                        affiliateLink: "https://s.shopee.com.br/4q9ucsYwXX",
                        rating: 4.9,
                        sold: "6mil+"
                      },
                      {
                        id: 93,
                        name: "Colchonete para Academia Premium 90x40x3 cm em Espuma D23 Impermeável para Yoga e Pilates",
                        origin: "BR",
                        price: "",
                        category: "Fitness e Musculação",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lzjhnmdxayw586@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/5q2RoyBgF5",
                        rating: 4.7,
                        sold: "70mil+"
                      },
                      {
                        id: 94,
                        name: "Bicicleta Elétrica Dobrável NUDA para Adultos com Pedal Assistido para Uso Urbano e Viagens",
                        origin: "BR",
                        price: "",
                        category: "Mobilidade Urbana",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mj0pubc1kdty09.webp",
                        affiliateLink: "https://s.shopee.com.br/5q2Rpj1Hv3",
                        rating: 4.7,
                        sold: "1mil+"
                      },  
                      {
                        id: 95,
                        name: "Kit Fantasia Coelha com Saia e Meia Arrastão para Carnaval",
                        origin: "BR",
                        price: "",
                        category: "Fantasias e Festas",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjao3ts7if4244.webp",
                        affiliateLink: "https://s.shopee.com.br/6VI8dLSn2p",
                        rating: 4.6,
                        sold: "204"
                      },
                      {
                        id: 96,
                        name: "Copo Térmico Inox 1.2L com Canudo e Protetor Floral Personalizado",
                        origin: "BR",
                        price: "",
                        category: "Cozinha e Bebidas",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mc0xo7cul3tz5e.webp",
                        affiliateLink: "https://s.shopee.com.br/gKLggrdxj",
                        rating: 4.9,
                        sold: "1mil+"
                      },
                      {
                        id: 97,
                        name: "HT VEST Conjunto de Biquíni com Detalhes Elegantes e Acabamento Refinado 2024 XX303",
                        origin: "BR",
                        price: "",
                        category: "Moda Praia",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-824gw-mfjl981r9b7w2f@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/5VPbTbbLhl",
                        rating: 4.8,
                        sold: "708"
                      },
                      {
                        id: 98,
                        name: "Fechadura Eletrônica Digital Intelar Wi-Fi Tuya 5 em 1 com Biometria, Bluetooth, Senha Touch, Chave e Tag",
                        origin: "BR",
                        price: "",
                        category: "Casa e Segurança",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-me7zojg4l5oh8e@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/3VeX6B7hZT",
                        rating: 4.9,
                        sold: "2mil+"
                      },
                      {
                        id: 99,
                        name: "Cadeira Gamer Profissional Ergonômica Reclinável para Escritório com Rodinhas e Apoio para Pés",
                        origin: "BR",
                        price: "",
                        category: "Móveis e Escritório",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-meh2ygcha0w363@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/1La2WJUeVU",
                        rating: 4.8,
                        sold: "8mil+"
                      },
                      {
                        id: 100,
                        name: "Óculos de Áudio Bluetooth Inteligentes para Esportes ao Ar Livre com Som Surround e Chamadas",
                        origin: "INT",
                        price: "",
                        category: "Eletrônicos e Acessórios",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rd3z-m7uwi4qo25hp4d.webp",
                        affiliateLink: "https://s.shopee.com.br/2Vlzud8V2j",
                        rating: 4.9,
                        sold: "416"
                      },    
                      {
                        id: 101,
                        name: "Escova de Limpeza de Teclado 8 em 1 Multifuncional Portátil para Computador",
                        origin: "BR",
                        price: "",
                        category: "Eletrônicos e Informática",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rffu-m3bogjn72exz86.webp",
                        affiliateLink: "https://s.shopee.com.br/AABVJI5fRp?share_channel_code=1",
                        rating: 4.9,
                        sold: "30mil+"
                      },
                      {
                        id: 102,
                        name: "Kit com 10 Peças de Pasta para Limpeza Profunda do Nariz com Carvão de Bambu para Cravos e Pontos Negros",
                        origin: "INT",
                        price: "",
                        category: "Beleza e Cuidados Pessoais",
                        image: "",
                        affiliateLink: "",
                        rating: 4.6,
                        sold: "90mil+"
                      },
                      {
                        id: 103,
                        name: "Fone de Ouvido Bluetooth 5.3 para Capacete de Motocicleta com Chamadas Mãos Livres à Prova D'Água",
                        origin: "BR",
                        price: "",
                        category: "Acessórios Automotivos",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-may7srwp8l8v25.webp",
                        affiliateLink: "https://s.shopee.com.br/4fqazRHx6Z",
                        rating: 4.9,
                        sold: "10mil+"
                      },
                      {
                        id: 104,
                        name: "Kit Capa de Chuva Pantaneiro Masculina e Feminina para Moto",
                        origin: "BR",
                        price: "",
                        category: "Acessórios Automotivos",
                        image: "https://down-br.img.susercontent.com/file/br-11134201-7qukw-leq5dzv8566820.webp",
                        affiliateLink: "https://s.shopee.com.br/9KcQYHfz04",
                        rating: 4.9,
                        sold: "240"
                      },
                      {
                        id: 105,
                        name: "Ventilador de Teto com Luz LED Silencioso Bivolt com Controle Remoto e Instalação Fácil E27",
                        origin: "BR",
                        price: "",
                        category: "Casa e Iluminação",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdxc-mbw853ewhik99c@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/4LDkbjirMC",
                        rating: 4.8,
                        sold: "40mil+"
                      },
                      {
                        id: 106,
                        name: "Conjunto Alfaiataria Social Feminino em Linho com Calça e Blusa",
                        origin: "BR",
                        price: "",
                        category: "Moda Feminina",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mer87de563gj6d.webp",
                        affiliateLink: "https://s.shopee.com.br/9KcQZB1lMe",
                        rating: 4.8,
                        sold: "80mil+"
                      },
                      {
                        id: 107,
                        name: "Body Splash Barbour's Beauty Feminino 200ml com Todas as Fragrâncias",
                        origin: "BR",
                        price: "",
                        category: "Beleza e Perfumes",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mdpfvko0aqj546.webp",
                        affiliateLink: "https://s.shopee.com.br/BOBerRrnM",
                        rating: 4.8,
                        sold: "7mil+"
                      },
                      {
                        id: 108,
                        name: "Camisola Feminina Sexy sem Bojo com Costas Abertas e Calcinha Regulável",
                        origin: "BR",
                        price: "",
                        category: "Moda Íntima",
                        image: "https://down-br.img.susercontent.com/file/1748a32f6d8be56b27994cbeb3121cb3@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/50TRPwZD8s",
                        rating: 4.9,
                        sold: "40mil+"
                      },
                      {
                        id: 109,
                        name: "Esponja Bucha de Silicone com Porta Sabão e Escova para Banho",
                        origin: "BR",
                        price: "",
                        category: "Beleza e Cuidados Pessoais",
                        image: "https://down-br.img.susercontent.com/file/sg-11134201-824hq-mf3260ltf85n36@resize_w450_nl.webp",
                        affiliateLink: "https://s.shopee.com.br/6AfOocDB3g",
                        rating: 4.7,
                        sold: "20mil+"
                      },
                      {
                        id: 110,
                        name: "Kit Jogo de Cama Edredom Casal Queen 06 Peças Dupla Face Super Macio Premium Casa Dona",
                        origin: "BR",
                        price: "",
                        category: "Cama, Mesa e Banho",
                        image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mgs0kysigc9187.webp",
                        affiliateLink: "https://s.shopee.com.br/60MJIMVuQW",
                        rating: 4.7,
                        sold: "490"
                    },
                    {
                      id: 111,
                      name: "Porta Sabão Líquido em Aço Inoxidável Ou Organizador de Talheres Giratorio Organização da Pia",
                      origin: "BR",
                      price: "",
                      category: "Cozinha e Organização",
                      image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mhcetsvuk2kg91.webp",
                      affiliateLink: "https://s.shopee.com.br/7VB75qyt0b",
                      rating: 4.9,
                      sold: "1mil+"
                  },
                  {
                    id: 112,
                    name: "Climatizador Smart 4 em 1 Resfria Ventila Umidifica e Purifica o Ar 3,5L Elgin",
                    origin: "BR",
                    price: "",
                    category: "Eletrodomésticos e Climatização",
                    image: "https://down-br.img.susercontent.com/file/sg-11134201-8258o-mfvgoq2oz47e73.webp",
                    affiliateLink: "https://s.shopee.com.br/156BoAHLt",
                    rating: 4.8,
                    sold: "7mil+"
                },         
                {
                  id: 113,
                  name: "Ventilador luminária 5 folhas grande de Teto com aroma silencioso e economico turbo controle remoto E27 Bivolt 50w",
                  origin: "BR",
                  price: "",
                  category: "Iluminação e Ventilação",
                  image: "https://down-br.img.susercontent.com/file/sg-11134201-825ay-mgf41gb080eh9d.webp",
                  affiliateLink: "https://s.shopee.com.br/5fjSwtknnU",
                  rating: 4.8,
                  sold: "2mil+"
              },                                                                                                                                                                      
];